name: CI

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -t release-devops -f Dockerfile Test-Project-DevOps

    - name: Run simple tests
      run: |
        docker run -d --name my-devops -p 5000:80 release-devops
        sleep 10
        curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 | grep 200
        docker stop my-devops
        docker rm my-devops
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yorgoa5/devops